### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by victoriousvictorvanquishes** [sponsianus/dishy_grafana#1]
$ docker-compose up -d  
Pulling netstats (docker.pkg.github.com/sponsianus/dishy_grafana/netstats:)...  
ERROR: Head https://docker.pkg.github.com/v2/sponsianus/dishy_grafana/netstats/manifests/latest: no basic auth credentials

**Comment by sponsianus** [comment]
Thanks!

Apparently, GH reg needs auth even for public images. My bad.

Pushed netstats image to Docker Hub and updated the compose file.
