### ISSUE TITLE
No speedtest results 

### ISSUE THREAD

**Issue by lioon** [sponsianus/dishy_grafana#6]
In the Network Statistics dashboard the speedtest result panels remain empty resp. "no data" is shown. Speedtest itself is executed properly.

**Comment by sponsianus** [comment]
Is the netstats container running? The netstats container feeds its data to the influx DB. Chances are there is a communications issue between the containers.

**Comment by lioon** [comment]
Yes, it is running. But I noticed, I get this error from the netstats container: 

> Error in plugin: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.21/info": dial unix /var/run/docker.sock: connect: permission denied

**Comment by sponsianus** [comment]
Is it possible the containers were started by a user without root access or by a user that was not added to the docker group?

The netstats image needs `privileged` access so it can collect the stats from Docker its self.

**Comment by lioon** [comment]
Netstats is running privileged, but I think you are right with the docker group. Figuring out how to solve this with MacOS and docker-compose. (/var/run/docker.sock is a symbolic link to $User/.docker/run/docker.sock)

**Comment by sponsianus** [comment]
For Mac should be `sudo dseditgroup -o edit -a <YOUR_USERNAME> -t user docker`
